services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fromherotozero
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123!
    ports:
      - "5433:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: fromherotozero
      DB_USER: postgres
      DB_PASSWORD: 123!